language: node_js
node_js:
  - 7
  - 8
  - 9
  - 10
  - 11
sudo: false
after_script:
 - npm i coveralls
 - cat ./coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls
services:
  - redis-server
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
